Algoritmo "teste-mesa-manual"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var
   x, y: inteiro


Inicio

   x <- 0
   y <- 4

   enquanto x < 3 faca
   y <- y+2
   x <-  x+1
   escreval (x, " -",y)
fimenquanto


Fimalgoritmo