Algoritmo "teste-condicional"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/07/2024
Var
   // Seção de Declarações das variáveis

   x: inteiro

Inicio

   x <- 5

   escreval ("Bom dia")

   se x < 0 entao
      escreval ("Boa tarde")
   fimse


   escreval ("Boa noite")





Fimalgoritmo