Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/07/2024
Var
   // Seção de Declarações das variáveis

  raio, area: real
Inicio

     escreval ("Digite o raio do circulo:")
     leia (raio)
     area  <- Pi * Exp(raio, 2)
     escreva("Area = ", area:5:3)
     
     

Fimalgoritmo