Algoritmo "Quadrante"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
   senha: inteiro

Inicio

   escreva ("Digite a senha: ")
   leia (senha)

   enquanto senha <> 2002 faca
      escreva ("Senha Invalida! Tente novamente: ")
      leia (senha)
   fimenquanto
   
   escreval ("Acesso Permitido!")


Fimalgoritmo